In [1]:
import numpy as np

In [2]:
# create the array
x = np.array([45,23,12,5,67,89,32,16])

In [3]:
print(x)

[45 23 12  5 67 89 32 16]


In [4]:
x

array([45, 23, 12,  5, 67, 89, 32, 16])

In [6]:
y = np.array([45,23.67,12,5,67,89,32,16])

In [7]:
y

array([45.  , 23.67, 12.  ,  5.  , 67.  , 89.  , 32.  , 16.  ])

In [8]:
y[5]

89.0

In [9]:
z = np.array([45,23.67,12,'hello',67,89,32,16])

In [10]:
z

array(['45', '23.67', '12', 'hello', '67', '89', '32', '16'], dtype='<U32')

In [11]:
x

array([45, 23, 12,  5, 67, 89, 32, 16])

In [12]:
x.dtype

dtype('int64')

In [13]:
x.shape

(8,)

In [14]:
x + 12

array([ 57,  35,  24,  17,  79, 101,  44,  28])

In [15]:
x * 1.34

array([ 60.3 ,  30.82,  16.08,   6.7 ,  89.78, 119.26,  42.88,  21.44])

In [16]:
x / 3.45

array([13.04347826,  6.66666667,  3.47826087,  1.44927536, 19.42028986,
       25.79710145,  9.27536232,  4.63768116])

In [17]:
# Linear equation
new = x * 3.4 + 12

In [18]:
new

array([165. ,  90.2,  52.8,  29. , 239.8, 314.6, 120.8,  66.4])

In [19]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [21]:
np.arange(4,15,2)

array([ 4,  6,  8, 10, 12, 14])

In [22]:
np.arange(12,4,-1)

array([12, 11, 10,  9,  8,  7,  6,  5])

In [23]:
np.arange(-5,5,0.25)

array([-5.  , -4.75, -4.5 , -4.25, -4.  , -3.75, -3.5 , -3.25, -3.  ,
       -2.75, -2.5 , -2.25, -2.  , -1.75, -1.5 , -1.25, -1.  , -0.75,
       -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,
        1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,
        4.  ,  4.25,  4.5 ,  4.75])

In [24]:
np.zeros(4)

array([0., 0., 0., 0.])

In [25]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
y = np.array([[1,5,7],[6,3,2],[7,8,2],[10,4,2]])

In [27]:
y

array([[ 1,  5,  7],
       [ 6,  3,  2],
       [ 7,  8,  2],
       [10,  4,  2]])

In [28]:
y.shape

(4, 3)

In [29]:
y.flatten()

array([ 1,  5,  7,  6,  3,  2,  7,  8,  2, 10,  4,  2])

In [30]:
y.reshape(3,4)

array([[ 1,  5,  7,  6],
       [ 3,  2,  7,  8],
       [ 2, 10,  4,  2]])

In [31]:
y.reshape(-1, 2)

array([[ 1,  5],
       [ 7,  6],
       [ 3,  2],
       [ 7,  8],
       [ 2, 10],
       [ 4,  2]])

In [32]:
y.reshape(3,-1)

array([[ 1,  5,  7,  6],
       [ 3,  2,  7,  8],
       [ 2, 10,  4,  2]])

In [33]:
y.reshape(3,2,2)

array([[[ 1,  5],
        [ 7,  6]],

       [[ 3,  2],
        [ 7,  8]],

       [[ 2, 10],
        [ 4,  2]]])

In [34]:
x

array([45, 23, 12,  5, 67, 89, 32, 16])

In [35]:
x[4:]

array([67, 89, 32, 16])

In [36]:
x[:5]

array([45, 23, 12,  5, 67])

In [40]:
y[0:3,1:3]

array([[5, 7],
       [3, 2],
       [8, 2]])

In [41]:
y

array([[ 1,  5,  7],
       [ 6,  3,  2],
       [ 7,  8,  2],
       [10,  4,  2]])

In [42]:
z = [6,4,2,3,6,5,4,3,9]

In [43]:
np.unique(z)

array([2, 3, 4, 5, 6, 9])

In [44]:
x.mean()

36.125

In [45]:
x.max()

89

In [46]:
x.sort()

In [47]:
x

array([ 5, 12, 16, 23, 32, 45, 67, 89])